version: '3.8'

services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - PGUSER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=messenger
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ldotexe/messenger-backend:latest

    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=messenger
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PW}
      - DB_NAME=messenger
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PW}
      - PGDATABASE=messenger

  frontend:
    image: ldotexe/messenger-frontend:latest
    restart: always
    stdin_open: true

  nginx:
    image: ldotexe/messenger-nginx:latest
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
      - frontend

volumes:
  db_data: